#!/usr/bin/env python3
"""LIT-3(a): zero-DFT *OOH fingerprint classification (docs/43 AMENDMENT 5, A5.3a).

Registered scope: every archived *OOH geometry is classified by O-O distance
as the PRIMARY fingerprint (hydroperoxo *O-OH ~1.37-1.45 A vs superoxo *OO-H
~1.30-1.32 A, Inico 2024), with Bader (QTAIM) charge via pp.x as the SECONDARY
check. The Bader leg is NOT computed here: Inico's charge thresholds are
Bader-defined and may not be compared against Loewdin values without
recalibration, and no `.save` directories survive on disk -- every run listed
in the `bader_todo` section needs one fixed-geometry SCF (bounded within the
~150-SCF A5.1a/A5.3a regeneration budget) plus pp.x before any charge
fingerprint exists. A scaling-residual audit accompanies the classification
(Man 3.2 +/- 0.2/0.4 as an RPBE-population outlier flag ONLY, never a
per-state pass/fail -- docs/41 P9's functional-mismatch caveat applies).

What is classified: every `s0_OOH*.out` RELAXATION under runs/ (production
runs, the Cr basin restart, the P10 orientation runs, the block-1A cellsym
rows that have returned). Fixed-geometry SCF outputs (the P7 U-ladders, the
docs/41 probe variants, the Cr k-mesh bridges, the Hessian stencil) share
their parent relaxation's geometry by construction and are listed as excluded
duplicates rather than classified twice.

Conventions REUSED, not reinvented:
  - energy QC: dft.qe_qc.trusted_energy_ev / scan (the production gate);
  - CHE referencing for the scaling audit: hea_oer.referencing.delta_G
    (ZPE-TS: OH +0.35 / OOH +0.40 eV, Man 2011 / Valdes 2008) -- the
    slab energy cancels in dG_OOH - dG_OH but the same helper is used anyway;
  - geometry parsing: probe_decks.parse_input_deck / parse_final_coordinates;
  - magnetisation readout: build_cellsym_pilot.final_magnetisation.

Outputs (the .md is REGENERATED by this script -- never hand-edit it):
  docs/research/lit3_ooh_fingerprints.json
  docs/research/2026-08-12-lit3-ooh-fingerprints.md

Usage:
  PYTHONPATH=src python src/dft/lit3_ooh_fingerprints.py [--root .]
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import math
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
sys.path.insert(0, os.path.join(_HERE, ".."))          # src/ on the path

from probe_decks import (parse_input_deck, parse_final_coordinates)  # noqa: E402
from build_cellsym_pilot import final_magnetisation                  # noqa: E402
from hea_oer.referencing import delta_G                              # noqa: E402
from dft import qe_qc                                                # noqa: E402

# ---------------------------------------------------------------------------
# Registered numbers (docs/43 A5.3a). The bands carry "~" in the registration;
# they are applied as stated numeric intervals and every value outside both
# bands is reported with its distance to the nearest band, never coerced.
# ---------------------------------------------------------------------------
BAND_HYDROPEROXO_A = (1.37, 1.45)
BAND_SUPEROXO_A = (1.30, 1.32)
MAN_INTERCEPT_EV = 3.2
MAN_SOFT_EV = 0.2
MAN_OUTLIER_EV = 0.4

#: scaling-audit chains: production energies per metal (strict QC). The Cr
#: *OOH energy of record is the GATE-1-passed basin restart (docs/41 s6f,
#: tier_v2); the production metastable row is audited alongside, labelled.
CHAINS = {
    "Ru": dict(run=os.path.join("runs", "Ru_anchor")),
    "Ir": dict(run=os.path.join("runs", "Ir_anchor")),
    "Cr": dict(run=os.path.join("runs", "Cr_slab"),
               ooh_override=os.path.join("runs", "probe", "Cr_basin",
                                         "s0_OOH.out"),
               note="*OOH of record = basin restart (GATE-1-passed, docs/41 "
                    "s6f); production metastable row audited alongside"),
    "Mn": dict(run=os.path.join("runs", "Mn_slab")),
    "Fe": dict(run=os.path.join("runs", "Fe_slab")),
    "Cu": dict(run=os.path.join("runs", "Cu_slab")),
}

REGISTERED_HOLES = [
    "Co: no *OOH run exists at any U (docs/41 s6d/s6e; docs/43 A5.5 "
    "firewall) -- the hole is registered, not papered over",
    "Ni: runs/Ni_slab *OOH chain rests on dft_eta.json.RETRACTED; no "
    "trusted Ni row exists",
]


def _mi_dist(p, q, cell):
    """Minimum-image distance, diagonal cell, a/b periodic (c = vacuum)."""
    a, b = cell[0][0], cell[1][1]
    dx = p[1] - q[1]
    dx -= a * round(dx / a)
    dy = p[2] - q[2]
    dy -= b * round(dy / b)
    dz = p[3] - q[3]
    return math.sqrt(dx * dx + dy * dy + dz * dz)


def layout(nat, species):
    """(n_slab, n_ads) for the *OOH cells this campaign has built.

    21 = 18-atom slab + OOH; 39 = 2x1 (36) + OOH; 40 = 2x1 + OOH + spectator
    *O (emitter order: working O, O, H, then spectator -- verified against
    the emitted decks). Returns None for anything else."""
    if nat == 21 and species[18:] == ["O", "O", "H"]:
        return 18, 3
    if nat == 39 and species[36:] == ["O", "O", "H"]:
        return 36, 3
    if nat == 40 and species[36:] == ["O", "O", "H", "O"]:
        return 36, 4
    return None


def classify_oo(d):
    lo, hi = BAND_SUPEROXO_A
    if lo <= d <= hi:
        return "superoxo (*OO-H band)"
    lo, hi = BAND_HYDROPEROXO_A
    if lo <= d <= hi:
        return "hydroperoxo (*O-OH band)"
    gaps = []
    for name, (lo, hi) in (("superoxo", BAND_SUPEROXO_A),
                           ("hydroperoxo", BAND_HYDROPEROXO_A)):
        gaps.append((min(abs(d - lo), abs(d - hi)), name))
    g, name = min(gaps)
    side = "between the registered bands" if BAND_SUPEROXO_A[1] < d < \
        BAND_HYDROPEROXO_A[0] else "outside both registered bands"
    return f"UNCLASSIFIED ({side}; nearest = {name}, {g:.3f} A away)"


def analyse_run(root, relout):
    inp = relout[:-4] + ".in"
    p_out, p_in = os.path.join(root, relout), os.path.join(root, inp)
    if not os.path.exists(p_in):
        return dict(run=relout.replace("\\", "/"), skip="no matching .in")
    deck = parse_input_deck(p_in)
    calc = (re.search(r"calculation\s*=\s*'(\w+)'", deck["raw"]) or
            [None, "?"])[1] if deck["raw"] else "?"
    if calc != "relax":
        return dict(run=relout.replace("\\", "/"), excluded=True,
                    calculation=calc,
                    note="fixed-geometry SCF: geometry duplicates its parent "
                         "relaxation; classified once, at the parent")

    pos, prov = parse_final_coordinates(p_out)
    qc = qe_qc.scan(p_out, p_in)
    txt = open(p_out, errors="replace").read()
    converged = "bfgs converged" in txt
    row = dict(run=relout.replace("\\", "/"), calculation="relax",
               qc_verdict=qc["verdict"], bfgs_converged=converged,
               geometry_provenance=prov)
    if pos is None:
        row["skip"] = "no coordinates parseable from the output"
        return row

    species = [q[0] for q in pos]
    lay = layout(len(pos), species)
    if lay is None:
        row["skip"] = (f"unrecognized cell layout (nat={len(pos)}, trailing "
                       f"species {species[-4:]})")
        return row
    n_slab, n_ads = lay
    cell = deck["cell"]
    ob, oo, h = pos[n_slab], pos[n_slab + 1], pos[n_slab + 2]

    # H host: the nearest O anywhere in the cell, labelled structurally
    best_i, best_d = None, 1e9
    for i, q in enumerate(pos):
        if q[0] != "O":
            continue
        d = _mi_dist(h, q, cell)
        if d < best_d:
            best_i, best_d = i, d
    if best_i == n_slab + 1:
        host = "adsorbate outer O (*O-OH connectivity)"
    elif best_i == n_slab:
        host = "adsorbate binding O"
    elif n_ads == 4 and best_i == n_slab + 3:
        host = "spectator *O"
    else:
        zmax = max(q[3] for q in pos[:n_slab] if q[0] == "O")
        host = ("slab bridging O (*OO-H connectivity)"
                if abs(pos[best_i][3] - zmax) < 0.5 else "slab O (in-plane)")

    # active-site metal under the binding O
    mbest, mbest_d = None, 1e9
    for i in range(n_slab):
        if pos[i][0] in ("O", "H"):
            continue
        d = _mi_dist(pos[i], ob, cell)
        if d < mbest_d:
            mbest, mbest_d = i, d

    oo_A = _mi_dist(ob, oo, cell)
    tot, ab = final_magnetisation(p_out)
    row.update(
        nat=len(pos), cell_arm=("1x1" if n_slab == 18 else "2x1"),
        oo_A=round(oo_A, 4), classification=classify_oo(oo_A),
        h_nearest_O=host, h_O_dist_A=round(best_d, 4),
        h_to_outer_O_A=round(_mi_dist(h, oo, cell), 4),
        h_to_binding_O_A=round(_mi_dist(h, ob, cell), 4),
        active_site=pos[mbest][0] if mbest is not None else None,
        M_Obind_A=round(mbest_d, 4) if mbest is not None else None,
        total_magnetization=tot, absolute_magnetization=ab,
        needs_scf_regeneration_for_bader=True)
    return row


def scaling_audit(root):
    rows = []
    for metal, cfg in CHAINS.items():
        rd = os.path.join(root, cfg["run"])
        e, why = {}, {}
        for tag, fname in (("slab", "slab.out"), ("OH", "s0_OH.out"),
                           ("OOH", "s0_OOH.out"), ("H2O", "H2O.out"),
                           ("H2", "H2.out")):
            p = os.path.join(rd, fname)
            if not os.path.exists(p):
                e[tag], why[tag] = None, "missing"
            else:
                e[tag] = qe_qc.trusted_energy_ev(p, strict=True)
                why[tag] = "failed strict QC"
        variants = [("production", e["OOH"])]
        if "ooh_override" in cfg:
            po = os.path.join(root, cfg["ooh_override"])
            e_basin = qe_qc.trusted_energy_ev(po, strict=True) \
                if os.path.exists(po) else None
            variants = [("gate1_passed_basin (value of record)", e_basin),
                        ("production_mirror (METASTABLE, docs/41 s6f -- "
                         "audited, not of record)", e["OOH"])]
        for label, e_ooh in variants:
            row = dict(metal=metal, source=cfg["run"].replace("\\", "/"),
                       ooh_energy=label, note=cfg.get("note", ""))
            missing = [(t, why.get(k, "failed strict QC"))
                       for t, k, v in (("slab", "slab", e["slab"]),
                                       ("s0_OH", "OH", e["OH"]),
                                       ("s0_OOH", "OOH", e_ooh),
                                       ("H2O", "H2O", e["H2O"]),
                                       ("H2", "H2", e["H2"])) if v is None]
            if missing:
                row["intercept_eV"] = None
                row["flag"] = ("NOT COMPUTABLE: " + ", ".join(
                    f"{t} ({w})" for t, w in missing))
                rows.append(row)
                continue
            dg_oh = delta_G(e["slab"], e["OH"], "OH", e["H2O"], e["H2"])
            dg_ooh = delta_G(e["slab"], e_ooh, "OOH", e["H2O"], e["H2"])
            x = dg_ooh - dg_oh
            dev = abs(x - MAN_INTERCEPT_EV)
            if dev <= MAN_SOFT_EV:
                flag = f"within Man 3.2 +/- {MAN_SOFT_EV}"
            elif dev <= MAN_OUTLIER_EV:
                flag = (f"outside +/- {MAN_SOFT_EV}, within +/- "
                        f"{MAN_OUTLIER_EV} (soft flag)")
            else:
                flag = (f"RPBE-population OUTLIER FLAG (|x - 3.2| = "
                        f"{dev:.3f} eV > {MAN_OUTLIER_EV}) -- flag only, "
                        "never a per-state pass/fail; docs/41 P9 "
                        "functional-mismatch caveat applies")
            row.update(dG_OH_eV=round(dg_oh, 4), dG_OOH_eV=round(dg_ooh, 4),
                       intercept_eV=round(x, 4), flag=flag)
            rows.append(row)
    return rows


def find_runs(root):
    included, excluded = [], []
    runs_root = os.path.join(root, "runs")
    for dirpath, dirnames, filenames in os.walk(runs_root):
        if "_hess" in os.path.basename(dirpath):
            excluded.append(dict(
                run=os.path.relpath(dirpath, root).replace("\\", "/") + "/*",
                note="Hessian displacement stencil: +/-0.02-bohr copies of "
                     "one parent geometry (block 1C), not independent *OOH "
                     "geometries"))
            dirnames[:] = []
            continue
        for f in sorted(filenames):
            if not (f.startswith("s0_OOH") and f.endswith(".out")):
                continue
            if "THROWAWAY" in f:
                excluded.append(dict(
                    run=os.path.relpath(os.path.join(dirpath, f),
                                        root).replace("\\", "/"),
                    note="marked THROWAWAY on disk"))
                continue
            included.append(os.path.relpath(os.path.join(dirpath, f), root))
    return sorted(included), excluded


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=".")
    ap.add_argument("--json-out", default=os.path.join(
        "docs", "research", "lit3_ooh_fingerprints.json"))
    ap.add_argument("--md-out", default=os.path.join(
        "docs", "research", "2026-08-12-lit3-ooh-fingerprints.md"))
    args = ap.parse_args()
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    candidates, excluded = find_runs(args.root)
    classified, skipped = [], []
    for rel in candidates:
        row = analyse_run(args.root, rel)
        if row.get("excluded"):
            excluded.append(dict(run=row["run"], note=row["note"]))
        elif "skip" in row:
            skipped.append(row)
        else:
            classified.append(row)
    classified.sort(key=lambda r: (r["run"].split("/")[-2], r["run"]))

    audit = scaling_audit(args.root)
    n_bader = sum(1 for r in classified)
    payload = dict(
        _meta=dict(
            generated=str(_dt.date.today()),
            script="src/dft/lit3_ooh_fingerprints.py",
            registration="docs/43-prereg-week1-factorial.md AMENDMENT 5, "
                         "A5.3(a) -- zero-DFT tranche",
            primary_fingerprint="O-O distance (registered bands: "
                                f"hydroperoxo {BAND_HYDROPEROXO_A} A, "
                                f"superoxo {BAND_SUPEROXO_A} A, Inico 2024; "
                                "the registration writes them with '~' and "
                                "they are applied as stated intervals)",
            secondary="Bader (QTAIM) via pp.x -- NOT computed here; see "
                      "bader_todo",
            tier_context="zero new DFT; geometric observables only. tier_v2 "
                         "is frozen and unchanged; tier_v3 does not exist.",
        ),
        classified=classified,
        skipped=skipped,
        excluded_fixed_geometry=excluded,
        scaling_residual_audit=dict(
            rule=f"x = dG_OOH - dG_OH vs Man {MAN_INTERCEPT_EV} +/- "
                 f"{MAN_SOFT_EV}/{MAN_OUTLIER_EV} eV; RPBE-population "
                 "outlier flag ONLY, never a per-state pass/fail (docs/41 "
                 "P9 functional-mismatch caveat)",
            rows=audit),
        registered_holes=REGISTERED_HOLES,
        bader_todo=dict(
            status="NOT ATTEMPTED (registered secondary; requires charge "
                   "densities that do not survive on disk)",
            what_each_run_needs="one fixed-geometry SCF at the archived "
                                "final geometry to regenerate the density "
                                "(A5.3a; part of the ~150-SCF A5.1a/A5.3a "
                                "regeneration budget) + pp.x + a Bader "
                                "partitioning, recalibrated on our own "
                                "unambiguous anchor states before Inico's "
                                "thresholds are applied",
            runs_needing_regeneration=n_bader),
    )

    jpath = os.path.join(args.root, args.json_out)
    os.makedirs(os.path.dirname(jpath), exist_ok=True)
    json.dump(payload, open(jpath, "w", encoding="utf-8"), indent=1)
    print(f"-> {args.json_out}  ({len(classified)} classified, "
          f"{len(skipped)} skipped, {len(excluded)} excluded)")

    write_markdown(os.path.join(args.root, args.md_out), payload)
    print(f"-> {args.md_out}")


# ---------------------------------------------------------------------------
# markdown report (regenerated wholesale; never hand-edited)
# ---------------------------------------------------------------------------
def write_markdown(path, p):
    L = []
    A = L.append
    A("# LIT-3(a) — *OOH O–O fingerprint classification (zero DFT)")
    A("")
    A(f"*Generated {p['_meta']['generated']} by `{p['_meta']['script']}`. "
      f"Registered under {p['_meta']['registration']}. Do not hand-edit — "
      "rerun the script.*")
    A("")
    A("## Scope")
    A("")
    A("- **Primary fingerprint (registered):** O–O distance — hydroperoxo "
      f"*O–OH ~{BAND_HYDROPEROXO_A[0]:.2f}–{BAND_HYDROPEROXO_A[1]:.2f} Å vs "
      f"superoxo *OO-H ~{BAND_SUPEROXO_A[0]:.2f}–{BAND_SUPEROXO_A[1]:.2f} Å "
      "(Inico 2024). The "
      "registration writes the bands with `~`; they are applied here as the "
      "stated intervals and out-of-band values are reported as such, never "
      "coerced.")
    A("- **Secondary (registered, NOT computed here):** Bader (QTAIM) charge "
      "via pp.x. Inico's thresholds are Bader-defined and may not be compared "
      "against Löwdin values without recalibration on our own anchor states. "
      "No `.save` directory survives on disk, so **every run below needs one "
      "fixed-geometry SCF + pp.x before any charge fingerprint exists** "
      "(bounded within the ~150-SCF A5.1a/A5.3a regeneration budget) — see "
      "the Bader section.")
    A("- Zero new DFT: geometric observables from archived outputs. tier_v2 "
      "is frozen and unchanged; tier_v3 does not exist.")
    A("")
    A("## Classification — every archived *OOH relaxation")
    A("")
    A("| run | cell | conv. | O–O (Å) | registered-band class | H sits on | "
      "H–O (Å) | tot/abs mag (μ_B) | QC |")
    A("|---|---|---|---|---|---|---|---|---|")
    for r in p["classified"]:
        mag = ("—" if r["total_magnetization"] is None else
               f"{r['total_magnetization']:g} / "
               f"{r['absolute_magnetization']:g}")
        conv = "yes" if r["bfgs_converged"] else "**NO**"
        A(f"| `{r['run']}` | {r['cell_arm']} | {conv} | {r['oo_A']:.3f} | "
          f"{r['classification']} | {r['h_nearest_O']} | "
          f"{r['h_O_dist_A']:.3f} | {mag} | {r['qc_verdict']} |")
    A("")
    n_unc = sum(1 for r in p["classified"]
                if r["classification"].startswith("UNCLASSIFIED"))
    n_conv = sum(1 for r in p["classified"] if r["bfgs_converged"])
    A(f"- {len(p['classified'])} geometries classified ({n_conv} from "
      f"converged relaxations); {n_unc} sit outside the two registered bands "
      "(between or beyond them) and are reported with their distance to the "
      "nearest band, never coerced into one.")
    if p["skipped"]:
        A(f"- {len(p['skipped'])} outputs skipped (no parseable geometry or "
          "unrecognized layout) — listed in the JSON.")
    A("- Unconverged rows (if any) are classified from their last-step "
      "geometry and marked; they are not relaxed minima and must not be "
      "quoted as such.")
    A("")
    A("## Excluded fixed-geometry outputs (geometry duplicates)")
    A("")
    A("The P7 U-ladders, the docs/41 probe variants (dipole/vac/RPBE/spin), "
    "the Cr k-mesh bridges and the block-1C Hessian stencil are "
    "fixed-geometry SCFs at a parent relaxation's coordinates: same "
    "geometry, so classifying them again would double-count. "
    f"{len(p['excluded_fixed_geometry'])} entries listed in the JSON.")
    A("")
    A("## Scaling-residual audit (Man 3.2 ± 0.2/0.4 — flag only)")
    A("")
    A("| metal | *OOH energy used | ΔG_OH | ΔG_OOH | x = ΔG_OOH−ΔG_OH (eV) | "
      "flag |")
    A("|---|---|---|---|---|---|")
    for r in p["scaling_residual_audit"]["rows"]:
        if r["intercept_eV"] is None:
            A(f"| {r['metal']} | {r['ooh_energy']} | — | — | — | "
              f"{r['flag']} |")
        else:
            A(f"| {r['metal']} | {r['ooh_energy']} | {r['dG_OH_eV']:.3f} | "
              f"{r['dG_OOH_eV']:.3f} | **{r['intercept_eV']:.3f}** | "
              f"{r['flag']} |")
    A("")
    A("Registered holes (reported, not repaired): "
      + " ".join(f"({i+1}) {h}" for i, h in
                 enumerate(p["registered_holes"])))
    A("")
    A("## Bader (registered secondary) — what it would take")
    A("")
    b = p["bader_todo"]
    A(f"- Status: **{b['status']}**.")
    A(f"- Runs needing charge-density regeneration: "
      f"**{b['runs_needing_regeneration']}** (every classified row; no "
      "`.save` survives).")
    A(f"- Per run: {b['what_each_run_needs']}.")
    A("")
    A("## Companion compute decks (prepared, NOT deployed)")
    A("")
    A("The A5.3(b) *OO-H spot check and A5.3(c) Cr conformer×spin factorial "
      "decks are built by `src/dft/build_lit3_ooh_anatomy.py` into "
      "`runs/probe/{Cr,Ir,Ru}_lit3/` with NOT-DEPLOYED manifests "
      "(`runs/probe/m_lit3_np20.txt`, `runs/probe/lit3_manifest.json`). "
      "docs/43 A5.7 gates any launch on the 1A manifest being drained, and "
      "the ±-spin-start reading needs sign-off first.")
    A("")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L))


if __name__ == "__main__":
    sys.exit(main())
