#!/usr/bin/env python
"""FWM feedstock weigh-sheet for the round-1 melt set (docs/15).

Converts each target composition (at.%) to elemental feedstock masses for a given
total charge mass, and applies a manganese over-charge (Mn evaporates during arc
melting). Emits a print-ready markdown sheet to stdout.

    PYTHONPATH=src python src/scripts/weigh_sheet.py --basis 10 --mn-overcharge 4
    # write the committed sheet:
    PYTHONPATH=src python src/scripts/weigh_sheet.py > docs/17-fwm-weigh-sheet.md

Mass fraction of element i for target atomic fractions x_i and molar masses M_i:
    w_i = x_i * M_i / sum_j(x_j * M_j)          mass_i = basis * w_i
The Mn weigh target is mass_Mn * (1 + overcharge/100); all others unchanged. The
nominal at.% is the design target — verify the *actual* composition by SEM-EDS after
melting, never assume nominal (HEAs segregate; Mn evaporates).
"""
from __future__ import annotations

import argparse
import datetime as _dt
import sys

# Standard atomic weights (g/mol), IUPAC.
MOLAR_MASS = {
    "Fe": 55.845, "Co": 58.933, "Ni": 58.693,
    "Cr": 51.996, "Mn": 54.938, "Cu": 63.546,
}

# Round-1 melt set — docs/15 §1. (name, role, {element: at.%})
MELT_SET = [
    ("Fe32Ni17Co34Mn18", "headline (Cr-free, sweep #1, eta 0.78 V)",
     {"Fe": 32, "Ni": 17, "Co": 34, "Mn": 18}),
    ("Cr6Fe33Ni27Mn34", "low-cost / abundant (sweep find)",
     {"Cr": 6, "Fe": 33, "Ni": 27, "Mn": 34}),
    ("Mn19Fe12Ni35Co16Cr18", "most-confident prediction (eta_std 0.15)",
     {"Mn": 19, "Fe": 12, "Ni": 35, "Co": 16, "Cr": 18}),
    ("Co20Ni20Cr20Mn20Cu20", "equiatomic reference (Cantor+Cu)",
     {"Co": 20, "Ni": 20, "Cr": 20, "Mn": 20, "Cu": 20}),
    ("Cr19Co28Fe25Ni28", "predicted-poor anchor (correlation range)",
     {"Cr": 19, "Co": 28, "Fe": 25, "Ni": 28}),
    ("FeCoNi", "ablation ternary (drop the HEA aspect)",
     {"Fe": 1, "Co": 1, "Ni": 1}),
]


def mass_breakdown(at_pct: dict[str, float], basis_g: float):
    """Return {element: (norm_at_frac, nominal_mass_g)} for a total charge `basis_g`."""
    tot_at = sum(at_pct.values())
    fracs = {el: v / tot_at for el, v in at_pct.items()}
    denom = sum(fracs[el] * MOLAR_MASS[el] for el in fracs)
    return {el: (fracs[el], basis_g * fracs[el] * MOLAR_MASS[el] / denom) for el in fracs}


def main() -> None:
    p = argparse.ArgumentParser(description="FWM feedstock weigh-sheet (round-1 melt set)")
    p.add_argument("--basis", type=float, default=10.0, help="total charge mass per button (g)")
    p.add_argument("--mn-overcharge", type=float, default=4.0, help="extra Mn, %% (evaporation)")
    args = p.parse_args()
    b, oc = args.basis, args.mn_overcharge
    try:  # Windows consoles default to cp1252, which can't encode the Sigma glyph
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:  # pragma: no cover
        pass

    out = []
    out.append("# 17 — FWM feedstock weigh-sheet (round-1 melt set)")
    out.append("")
    out.append(f"> Auto-generated by [`src/scripts/weigh_sheet.py`](../src/scripts/weigh_sheet.py) "
               f"on {_dt.date.today().isoformat()} for a **{b:.1f} g** charge per button and a "
               f"**+{oc:.0f}% Mn over-charge**. Re-run with `--basis`/`--mn-overcharge` to rescale. "
               f"Compositions and roles: [docs/15](15-round1-melt-test-plan.md) §1.")
    out.append("")
    out.append("**Procedure.** Weigh each element to the **weigh target (g)** column (Mn already "
               "includes the over-charge; all others = nominal). Arc/button-melt, flip + remelt "
               ">=3x, homogenize ~1000-1100 C. **Verify the actual composition by SEM-EDS** — the "
               "at.% column is the *design target*, not a guarantee (Mn evaporates; HEAs segregate). "
               "Scale linearly for a different button size (masses double at 20 g, etc.).")
    out.append("")

    for name, role, at_pct in MELT_SET:
        out.append(f"## {name}")
        out.append(f"*{role}*  ·  total charge **{b:.1f} g**")
        out.append("")
        out.append("| Element | at.% | molar mass (g/mol) | nominal mass (g) | **weigh target (g)** |")
        out.append("|---|---|---|---|---|")
        bd = mass_breakdown(at_pct, b)
        weigh_total = 0.0
        for el in sorted(at_pct, key=lambda e: -at_pct[e]):
            frac, m = bd[el]
            if el == "Mn":
                wt = m * (1 + oc / 100.0)
                cell = f"**{wt:.3f}**  _(+{oc:.0f}% Mn)_"
            else:
                wt = m
                cell = f"{wt:.3f}"
            weigh_total += wt
            out.append(f"| {el} | {frac * 100:.1f} | {MOLAR_MASS[el]:.3f} | {m:.3f} | {cell} |")
        out.append(f"| **Σ** | 100.0 | — | {b:.3f} | **{weigh_total:.3f}** |")
        out.append("")

    out.append("---")
    out.append("")
    out.append("**Safety (file with the SRC risk assessment):** metal dust during weighing/electrode "
               "prep (fume hood / N95); Cr-bearing alloys (#2–#5) → potential **Cr(VI)** under anodic "
               "OER (hazardous-waste handling). The headline pick **Fe32Ni17Co34Mn18 is Cr-free** — "
               "the cleanest first melt.")
    print("\n".join(out))


if __name__ == "__main__":
    main()
