#!/usr/bin/env python3
"""Regenerate tests/silentgate/fixtures/manifest.toml from the tracked corpus.

Run from anywhere:  python tests/silentgate/fixtures/regenerate_manifest.py

Every value in the manifest is MEASURED here, never transcribed. Run this when a
test tells you to -- a new symmetry-header form appeared, a decomposition file
was added, a fixture legitimately changed -- and commit the diff so the change is
visible rather than silent.

WHAT THIS DELIBERATELY DOES NOT COMPUTE
---------------------------------------
No census. No LOCKED verdict. No per-atom / per-axis / per-step exact-zero
determination. Those are `silentgate/readers/*` and `silentgate/census.py`, which
are core: "written and committed only by the entrant" (docs/43:1840). This
records file SHAPE -- hashes, byte counts, which marker lines a file carries, how
many force blocks and contribution blocks it has -- and stops there. Numeric
census expectations enter the suite later as golden files generated by the
entrant's own core.

AUTHORSHIP: written by AI as "tests and fixtures" under the A9.1 :1840 permitted
list.
"""
from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
DST = os.path.join(HERE, "manifest.toml")

# (path, what it pins, what question it decides)
FIXTURES = [
    ("runs/probe/Ir/s0_O__base.out",
     "LOCKED on both lateral axes; the 4-operation header",
     "that a two-axis lock is representable at all -- the legacy detector reads only F_y"),
    ("runs/probe/Ir/s0_OOH__base.out",
     "LOCKED on y while x is genuinely nonzero; the 2-operation header",
     "that the direction map distinguishes axes rather than returning a boolean"),
    ("runs/Ru_anchor/s0_O.out",
     "multi-step LOCKED, 27 ionic steps; smallest member of the gating 9",
     "that every step is censused, not just the last"),
    ("runs/Cu_slab/s0_OOH.out",
     "clean NOT-locked, 6 steps, No symmetry found",
     "the comfortable end of the 0-of-11 gate"),
    ("runs/Ni_slab/s0_O.out",
     "the 0-of-11 gate's weakest link: one adsorbate column prints zero on 7 of 9 steps",
     "that any tolerance, any last-step-only shortcut, or any dropped step turns this "
     "into a false LOCKED and voids the registered 0-of-11"),
    ("runs/probe/Ir/s0_O__dipole+vac32.out",
     "aborted run: banner, namelist error, MPI_ABORT, no header, no force block",
     "that an aborted output is reported, never silently counted as not-locked"),
    ("runs/Cu_slab/s0_OH.out",
     "complete header, zero force blocks -- one of the two registered unclassifiable rows",
     "that unscorable is a third outcome, distinct from LOCKED and not-LOCKED (:1864)"),
    ("runs/s0/d_hess_timing/s0_OOH__2x1v_mir__hess_a37xp.out",
     "force-only FALSE POSITIVE: nosym and noinv both set, No symmetry found, "
     "yet the adsorbate y-column is exactly zero",
     "that force-only mode has a nonzero false-positive rate on QE data, which the "
     "OC20 control cannot see because it certifies the trajectory reader only (:1858)"),
    ("runs/probe/Ru/s0_OH__dipole.out",
     "the ANY-vs-ALL quantifier flip: one adsorbate atom prints -0.00000000 on y, "
     "another does not",
     "the registered n/n agreement count -- 96/96 under ALL-atoms, 95/96 under ANY-atom"),
    ("runs/s0/i_cutoff_ladder/tio2__ecut60.out",
     "force-DECOMPOSITION false split: one real force block plus six contribution "
     "blocks, all using the identical `atom N type M force =` line format",
     "that force blocks are delimited rather than regex-scraped; the legacy "
     "FORCE_BLOCK finditer counts 7x the ionic steps here"),
    ("runs/probe/Cr/s0_OOH__base.out",
     "NUL-spliced output: MPI abort text written into the middle, the "
     "`Forces acting on atoms` header destroyed, the block starting at atom 12 of 21",
     "whether a truncated force block is scorable -- three archived LOCKED rows rest "
     "on blocks missing their first atoms"),
    ("runs/s3/Ni/s0_O__1x1_off__g1.out",
     "an x-axis force-only false positive inside live S3 production data",
     "that the x axis is censused; the legacy detector cannot see an x-lock at all"),
    ("runs/Co_slab/s0_O.out",
     "if_pos = 0 atoms printing NONZERO forces",
     "the correction of record filed 2026-08-27 against docs/43:1834"),
]

CONTRIB = re.compile(
    rb"^\s*The .{0,40}(?:contrib\.|contribution|correction term)\s+to forces\s*$", re.M)
FHDR = re.compile(rb"^\s*Forces acting on atoms", re.M)
FLINE = re.compile(rb"^\s*atom\s+\d+\s+type\s+\d+\s+force\s*=", re.M)
NAT = re.compile(rb"number of atoms/cell\s*=\s*(\d+)")
SYM = re.compile(rb"^.*?(\d+)\s+Sym\.\s*Ops\..*$", re.M)

HEADER = '''# FIXTURE MANIFEST for the `silentgate` S1 test suite.
#
# GENERATED -- do not hand-edit the values. Regenerate with
#   python tests/silentgate/fixtures/regenerate_manifest.py
# and commit the diff, so a corpus change is visible rather than silent.
#
# WHAT IS AND IS NOT IN THIS FILE
# -------------------------------
# Every fixture is an EXISTING TRACKED FILE, cited by path. Nothing is copied:
# `runs/` is fully committed, so the corpus is already in the repo and
# duplicating megabytes of it would only create a second thing to drift.
#
# The recorded values are STRUCTURAL -- hashes, byte counts, which marker lines
# a file contains, how many force blocks and contribution blocks it has. They
# are file-shape facts, checkable with a hash and a substring search.
#
# No test in this suite asserts a census value or a LOCKED verdict. Machine-
# checked expectations are structural only; numeric ones enter later as GOLDEN
# FILES generated by the entrant's core and reviewed by him (tests/silentgate/
# README.md). Nothing here scores the detector.
#
# BUT READ THIS BEFORE TRUSTING THE PROSE. The `pins` and `decides` strings say
# things like "LOCKED on both lateral axes" and "the adsorbate y-column is
# exactly zero". Those ARE verdicts, and they came from an AI-written survey of
# the corpus run on 2026-08-27 -- preserved, with what it measured and why it
# needs disclosing, at docs/research/ai-survey-2026-08-27/. They are prose
# explaining why each fixture was chosen. They are not assertions, no test reads
# them, and they carry no more authority than the survey that produced them.
#
# So each fixture records what it PINS (the shape, machine-checked) and what it
# DECIDES (the question the entrant's core has to answer correctly on it, prose).
#
# HASHES ARE LF-NORMALISED ON PURPOSE. `.gitattributes` carries no rule for
# *.out and core.autocrlf=true on the entrant's machine, so the same tracked
# blob is CRLF in the Windows working tree and LF on Linux CI. sha256_lf is
# computed after CRLF -> LF, so it is identical in both places. git_blob is the
# blob SHA-1 git actually tracks, recorded as provenance.
#
# AUTHORSHIP: written by AI as "fixtures" under the A9.1 :1840 permitted list.
'''

CORPUS_NOTE = '''
# ---------------------------------------------------------------------------
# CORPUS-WIDE INVARIANTS
#
# Tripwires on the archive, not on the detector. The corpus is allowed to GROW
# -- S3 is live -- so the suite checks that nothing DISAPPEARS and that no
# unrecognised symmetry-header form appears, rather than freezing the counts.
'''

HEADER_FORM_NOTE = '''# The pw.x symmetry header has FOUR distinct textual forms in this repo's own
# corpus. A9.1 :1836 registers that the reader "accepts both forms by regex and
# logs the form encountered per file", where "both" means the count-first form
# of pw.x 7.5 and the count-LAST form shown in symops_audit.py's own docstring
# ("Sym. Ops., with inversion, found          4 symmetry operations").
#
# Measured: ZERO files here use the count-last form, and FOUR count-first
# variants do. A regex anchored on "(no inversion)" misses 32 of the 173 files
# that carry a header.
#
# The count-last form has now been looked for OUTSIDE this repo too and not
# found. A9.7's act-2 dated line (2026-08-23, the first parse) validated four
# RuO2 4-layer Xu outputs and records: "all four are the count-first form; the
# older docstring form was not encountered; no reader fix is needed and the
# both-forms-by-regex rule stands". Their exact text, `4 Sym. Ops. (no
# inversion) found` / `2 Sym. Ops. (no inversion) found`, is the same variant as
# the 13 in-house files below.
#
# So the both-forms requirement is registered but has never been exercised
# against real count-last data anywhere -- 0 in-house, 0 in the four Xu files
# read. P-XU's six blind metals are still unread, so the form cannot be ruled
# out for them. Recorded so "accepts both forms" is not mistaken for "tested on
# both forms".'''

DECOMP_NOTE = '''# Files carrying force-DECOMPOSITION blocks. Each has ONE real force block and
# SIX contribution blocks in the identical `atom N type M force =` format, so a
# regex that scrapes force lines without delimiting blocks reads 7x the ionic
# steps and mixes partial forces into the census. None currently carries an
# adsorbate tag, so no archived CSV row is wrong -- but a per-step detector that
# inherits this bug is wrong on every one of them.'''


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def header_form_label(line):
    inv = "with-inversion" if ", with inversion," in line else "no-inversion"
    frac = "with-fractional-translation" if "fractional translation" in line else "bare"
    return "count-first, %s, %s" % (inv, frac)


def main():
    os.chdir(ROOT)
    out = [HEADER]
    for rel, pins, decides in FIXTURES:
        if not os.path.exists(rel):
            raise SystemExit("FATAL: fixture %s is missing" % rel)
        b = open(rel, "rb").read()
        lf = b.replace(b"\r\n", b"\n")
        blob = subprocess.run(["git", "hash-object", rel],
                              capture_output=True, text=True).stdout.strip()
        m = SYM.search(b)
        symline = m.group(0).decode("utf8", "replace").strip() if m else None
        nat = NAT.search(b)
        idx = b.find(b"Forces acting on atoms")
        region = b[idx:idx + 4000] if idx >= 0 else b
        fm = re.search(rb"^\s*atom\s+(\d+)\s+type", region, re.M)

        out.append("[[fixture]]")
        out.append('path = "%s"' % esc(rel))
        out.append('pins = "%s"' % esc(pins))
        out.append('decides = "%s"' % esc(decides))
        out.append('git_blob = "%s"' % blob)
        out.append('sha256_lf = "%s"' % hashlib.sha256(lf).hexdigest())
        out.append("bytes_lf = %d" % len(lf))
        out.append("")
        out.append("[fixture.structure]")
        out.append("pwscf_banner = %s" % ("true" if b"Program PWSCF" in b else "false"))
        if symline:
            out.append('symmetry_header = "%s"' % esc(symline))
            out.append('symmetry_header_form = "%s"' % header_form_label(symline))
            out.append("n_symops_in_header = %s" % m.group(1).decode())
        else:
            out.append('symmetry_header = ""')
            out.append('symmetry_header_form = "none"')
        out.append("no_symmetry_found = %s" % ("true" if b"No symmetry found" in b else "false"))
        out.append("n_force_block_headers = %d" % len(FHDR.findall(b)))
        out.append("n_contribution_block_headers = %d" % len(CONTRIB.findall(b)))
        out.append("n_force_lines = %d" % len(FLINE.findall(b)))
        out.append("n_atoms_cell = %s" % (nat.group(1).decode() if nat else "0"))
        out.append("first_force_atom_index = %s" % (fm.group(1).decode() if fm else "0"))
        out.append("nul_bytes = %d" % b.count(b"\x00"))
        out.append("negative_zero_tokens = %d" % b.count(b"-0.00000000"))
        out.append("job_done = %s" % ("true" if b"JOB DONE" in b else "false"))
        out.append("mpi_abort = %s" % ("true" if b"MPI_ABORT" in b else "false"))
        out.append("")

    files = [f for f in subprocess.run(["git", "ls-files", "runs/"], capture_output=True,
                                       text=True).stdout.split() if f.endswith(".out")]
    forms, nosym_only, neither, decomp = {}, 0, 0, []
    for f in files:
        b = open(f, "rb").read().replace(b"\r\n", b"\n")
        m = SYM.search(b)
        if m:
            key = re.sub(r"\d+", "N", m.group(0).decode("utf8", "replace").strip())
            forms[key] = forms.get(key, 0) + 1
        elif b"No symmetry found" in b:
            nosym_only += 1
        else:
            neither += 1
        if CONTRIB.search(b):
            decomp.append(f)

    out.append(CORPUS_NOTE)
    out.append("[corpus]")
    out.append("tracked_out_files = %d" % len(files))
    out.append("with_symmetry_header = %d" % sum(forms.values()))
    out.append("no_symmetry_found_only = %d" % nosym_only)
    out.append("neither_marker = %d" % neither)
    out.append("with_force_decomposition_blocks = %d" % len(decomp))
    out.append("")
    out.append(HEADER_FORM_NOTE)
    out.append("[corpus.header_forms]")
    for k, v in sorted(forms.items(), key=lambda kv: -kv[1]):
        out.append('"%s" = %d' % (esc(k), v))
    out.append("")
    out.append(DECOMP_NOTE)
    out.append("[corpus.force_decomposition_files]")
    out.append("paths = [")
    for f in decomp:
        out.append('  "%s",' % esc(f))
    out.append("]")
    out.append("")

    with open(DST, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote %s" % os.path.relpath(DST, ROOT))
    print("  fixtures %d | tracked .out %d | header forms %d | decomposition files %d"
          % (len(FIXTURES), len(files), len(forms), len(decomp)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
