#!/usr/bin/env python
"""FWM feedstock weigh-sheet for the thermal round-0 melt set (docs/24 SS4).

Round 0 is the CALIBRATION set — heuristic-designed, melted before the oracle
exists (ML-designed compositions arrive in round 1, frozen in git first). Unlike
the catalysis sheet (docs/17, at.%), Cu-Fe DPMMC compositions follow the
literature convention of WEIGHT percent; the at.% column is derived (it feeds
the KKR-CPA inputs, which want atomic fractions).

Cr and Zr charges are too small to weigh as pure metal at button scale, so they
are delivered via Cu-master alloys; the Cu the master brings is subtracted from
the pure-Cu charge. Master compositions are ASSUMPTIONS until G0 confirms what
FWM stocks — override with --cr-master/--zr-master and regenerate.

    PYTHONPATH=src python src/thermo/weigh_sheet_round0.py --basis 20
    # write the committed sheet:
    PYTHONPATH=src python src/thermo/weigh_sheet_round0.py > docs/27-round0-weigh-sheet.md
"""
from __future__ import annotations

import argparse
import datetime as _dt
import sys

# Standard atomic weights (g/mol), IUPAC.
MOLAR_MASS = {"Cu": 63.546, "Fe": 55.845, "Cr": 51.996, "Zr": 91.224, "Ag": 107.868}

# Elements delivered via Cu-master alloys (element -> CLI default wt.% in master).
MASTER_DEFAULT = {"Cr": 10.0, "Zr": 33.0}

# Round-0 melt set — docs/24 SS4. (name, role, {element: wt.%}; Cu = balance)
MELT_SET = [
    ("Cu (OFHC control)", "rho-SOP calibration - G1: within 2% of handbook (1.724 uOhm-cm / 100 %IACS)", {}),
    ("C18150 clone (Cu-1.0Cr-0.1Zr)", "commercial positive control - expect ~450-545 MPa @ 80-90 %IACS",
     {"Cr": 1.0, "Zr": 0.1}),
    ("Cu-2Fe", "dilute spine end - doubles as the MuST CPA dilute-slope cross-check", {"Fe": 2.0}),
    ("Cu-6Fe", "spine", {"Fe": 6.0}),
    ("Cu-10Fe", "spine - likely sweet-spot region", {"Fe": 10.0}),
    ("Cu-14Fe", "literature comparison - best published Cu-14Fe: 907 MPa @ 54.3 %IACS drawn", {"Fe": 14.0}),
    ("Cu-10Fe-0.5Ag", "microalloy probe 1 - Ag strengthens with minimal conductivity penalty",
     {"Fe": 10.0, "Ag": 0.5}),
    ("Cu-10Fe-0.3Cr", "microalloy probe 2 - C18150 precipitation chemistry on the Fe spine",
     {"Fe": 10.0, "Cr": 0.3}),
]


def at_pct(wt: dict[str, float]) -> dict[str, float]:
    """wt.% dict (Cu = balance) -> at.% dict including Cu."""
    full = dict(wt)
    full["Cu"] = 100.0 - sum(wt.values())
    mol = {el: w / MOLAR_MASS[el] for el, w in full.items()}
    tot = sum(mol.values())
    return {el: 100.0 * m / tot for el, m in mol.items()}


def charges(wt: dict[str, float], basis_g: float, master_pct: dict[str, float]):
    """Return ([(feedstock label, grams)], warnings) for one melt.

    Master arithmetic: to deliver m grams of element X from a Cu-X master at
    p wt.% X, weigh m/(p/100) grams of master; it also delivers master*(1-p/100)
    grams of Cu, subtracted from the pure-Cu charge. Totals stay == basis_g.
    """
    rows, warnings = [], []
    cu_needed = basis_g * (100.0 - sum(wt.values())) / 100.0
    for el, w in wt.items():
        m_el = basis_g * w / 100.0
        if el in master_pct:
            p = master_pct[el]
            m_master = m_el / (p / 100.0)
            rows.append((f"Cu-{p:g}{el} master", m_master))
            cu_needed -= m_master * (1 - p / 100.0)
            if m_master < 0.1:
                warnings.append(
                    f"{el} master charge is {m_master*1000:.0f} mg - needs an analytical "
                    f"balance (or melt a bigger button and section it)")
        else:
            rows.append((el, m_el))
    rows.insert(0, ("Cu (OFHC)", cu_needed))
    if cu_needed < 0:
        warnings.append("master alloys deliver more Cu than the balance allows - use a richer master")
    return rows, warnings


def main() -> None:
    p = argparse.ArgumentParser(description="FWM feedstock weigh-sheet (thermal round-0)")
    p.add_argument("--basis", type=float, default=20.0, help="total charge mass per button (g)")
    for el, d in MASTER_DEFAULT.items():
        p.add_argument(f"--{el.lower()}-master", type=float, default=d,
                       help=f"wt.%% {el} in the Cu-{el} master alloy (CONFIRM AT G0)")
    args = p.parse_args()
    b = args.basis
    master_pct = {el: getattr(args, f"{el.lower()}_master") for el in MASTER_DEFAULT}
    try:  # Windows consoles default to cp1252
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:  # pragma: no cover
        pass

    out = []
    out.append("# 27 — FWM feedstock weigh-sheet (thermal round-0 calibration set)")
    out.append("")
    out.append(f"> Auto-generated by [`src/thermo/weigh_sheet_round0.py`](../src/thermo/weigh_sheet_round0.py) "
               f"on {_dt.date.today().isoformat()} for a **{b:.1f} g** charge per button. Master-alloy "
               f"assumptions: " + ", ".join(f"Cu-{v:g}{el}" for el, v in master_pct.items()) +
               " — **confirm what FWM stocks at G0** and regenerate with "
               "`--cr-master`/`--zr-master` if different. Compositions and roles: "
               "[docs/24](24-thermal-pivot-execution-plan.md) §4.")
    out.append("")
    out.append("**Procedure.** All compositions in **wt.%** (Cu-Fe literature convention); the at.% "
               "row feeds the KKR-CPA inputs. Arc-melt on a water-cooled hearth with **Ti getter**, "
               "flip + remelt ≥3×; for VIM heats use **phosphor-copper deoxidation 0.02–0.05 wt.%** "
               "(O < 5 ppm — oxygen is the #1 conductivity artefact, docs/24 §10). **Verify actual "
               "composition by SEM-EDS and check density** — nominal is the design target. Cut each "
               "button: one slice for hardness + eddy-current screening, rest for the draw route.")
    out.append("")
    out.append("**Before the first melt (hard gates):** the dated SRC risk-assessment paperwork "
               "(docs/25 — the Rules Wizard flags melt/draw as hazardous activities) and the G0 "
               "feedstock/SOP confirmations (tasks/todo.md).")
    out.append("")

    totals: dict[str, float] = {}
    for i, (name, role, wt) in enumerate(MELT_SET, 1):
        out.append(f"## {i}. {name}")
        out.append(f"*{role}*  ·  total charge **{b:.1f} g**")
        out.append("")
        ap = at_pct(wt)
        out.append("nominal at.%: " + ", ".join(f"{el} {v:.2f}" for el, v in sorted(ap.items(), key=lambda kv: -kv[1])))
        out.append("")
        out.append("| Feedstock | **weigh target (g)** |")
        out.append("|---|---|")
        rows, warnings = charges(wt, b, master_pct)
        for label, grams in rows:
            out.append(f"| {label} | **{grams:.3f}** |")
            totals[label] = totals.get(label, 0.0) + grams
        out.append(f"| **Σ** | **{sum(g for _, g in rows):.3f}** |")
        for w in warnings:
            out.append(f"\n> ⚠ {w}")
        out.append("")

    out.append("## Shopping list (whole set, +20% spare)")
    out.append("")
    out.append("| Feedstock | set total (g) | order (g, +20%) |")
    out.append("|---|---|---|")
    for label in sorted(totals, key=lambda k: -totals[k]):
        out.append(f"| {label} | {totals[label]:.2f} | {totals[label]*1.2:.1f} |")
    out.append("")
    out.append("---")
    out.append("")
    out.append("**Safety (file with the SRC risk assessment):** Cu/metal fume during melting "
               "(ventilation per FWM SOP); fine metal dust during weighing (N95); Cr-bearing charges "
               "(#2, #8) handled as metal powder/master chips — no Cr(VI) risk in this project "
               "(no anodic electrochemistry), but note it in the paperwork. Hot work + wire drawing "
               "under FWM supervision per the mentor agreement.")
    print("\n".join(out))


if __name__ == "__main__":
    main()
